# Site settings
title: My Blog and Portfolio
email: jstathopulos@gmail.com
description: "Displays both my thoughts on tech and life as well as my portfolio of the various project I done over the years"
baseurl: ""
url: "http://spiritbeaker226.github.io/"
twitter_username: JasonStats
github_username:  SpiritBreaker226

# Build settings
markdown: kramdown
permalink: pretty
